<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlvQMfB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlvQMfB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUlvQMfB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUlvQMfB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUlvQMfB\App_KernelDevDebugContainer([
    'container.build_hash' => 'UlvQMfB',
    'container.build_id' => '4b823eca',
    'container.build_time' => 1607613775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlvQMfB');
