<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpxrrS3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpxrrS3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMpxrrS3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMpxrrS3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMpxrrS3\App_KernelDevDebugContainer([
    'container.build_hash' => 'MpxrrS3',
    'container.build_id' => 'a0e5473c',
    'container.build_time' => 1607611223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpxrrS3');
